################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
ti/msp432/adc14.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/adc14.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/aes256.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/aes256.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/comp_e.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/comp_e.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/cpu.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/cpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/crc32.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/crc32.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/cs.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/cs.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/dma.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/dma.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/flash.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/flash.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/fpu.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/fpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/gpio.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/gpio.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/i2c.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/i2c.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/interrupt.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/interrupt.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/mpu.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/mpu.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/pcm.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/pcm.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/pmap.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/pmap.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/pss.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/pss.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/ref_a.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/ref_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/reset.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/reset.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/rtc_c.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/rtc_c.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/spi.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/spi.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/sysctl.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/sysctl.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/systick.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/systick.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/timer32.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/timer32.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/timer_a.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/timer_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/uart.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/uart.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ti/msp432/wdt_a.obj: C:/uoc\ sistemas\ ciberfisicos/workspace/PEC5_modificado/ti/msp432/wdt_a.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP432 Compiler'
	"C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/freertos/cortex-m4" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/board" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/oslib" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/include" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cc3100/simplelink/source" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/cmsis" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/graphics" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/inc" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/lcd" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/msp432" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/ti/sensors" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_cc3100_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_edu_boosterpack" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/uoc/ti_msp432_launchpad" --include_path="C:/uoc sistemas ciberfisicos/workspace/PEC5_modificado/projects/PEC5_1" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/uoc sistemas ciberfisicos/ccsV910_nou/ccs/tools/compiler/ti-cgt-arm_18.12.2.LTS/include" --define=__MSP432P401R__ --define=ARM_MATH_CM4 --define=TARGET_IS_MSP432P4XX --define=ccs -g --c99 --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ti/msp432/$(basename $(<F)).d_raw" --obj_directory="ti/msp432" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


